version: '3.8'

services:
  db:
    image: postgres:16
    container_name: gestor_vehiculos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Gestor_vehiculos
    ports:
      - 5431:5432